/**
 * thumb.js — maps a served web-photo path to its thumbnail equivalent.
 *
 * Three photo tiers exist:
 *   /public/photos/       full-res originals   (gitignored, archive only)
 *   /public/photos-web/   1600px JPEG          (lightbox, hero, large frames)
 *   /public/photos-thumb/  800px WebP          (grids — this file's concern)
 *
 * Thumbnails are generated by `npm run generate-thumbs` (backfill) and
 * automatically by `npm run import-photos` for new photos. Both write to
 * photos-thumb/<slug>/<name>.webp, mirroring the photos-web layout.
 */

/**
 * '/photos-web/tokyo/_MG_4580.JPG' → '/photos-thumb/tokyo/_MG_4580.webp'
 *
 * Returns the input unchanged for anything that isn't a photos-web path
 * (placeholders, external URLs, null) so callers can use it unconditionally.
 */
export function thumbSrc(src) {
  if (!src || !src.startsWith('/photos-web/')) return src;
  return src
    .replace('/photos-web/', '/photos-thumb/')
    .replace(/\.(jpe?g|png)$/i, '.webp');
}
